In [1]:
import numpy as np
import pandas as pd

# Cleaning Data

In [66]:
yerevan_actual_raw = pd.read_excel('./data/Yerevan actual.xlsx')

### filtering out duplicated in id

In [67]:
yerevan_actual_raw = yerevan_actual_raw.sort_values(by=['index'], ascending=False)
duplicates = yerevan_actual_raw.duplicated(subset=['id'])
yerevan_actual = yerevan_actual_raw[~duplicates].drop_duplicates(subset=['id'])

## trying to categorize house district

In [54]:
!pip install geopy

zsh:1: command not found: pip

In [68]:
import geopy
from geopy.geocoders import Nominatim
import pandas as pd

geolocator = Nominatim(user_agent="my_application")
# data.to_excel("districts1.xlsx", index=False)
data = yerevan_actual.head(100)
# Define a function to extract the district information from a location
def get_district(lat, lng):
    # Reverse geocode the coordinates to get the address
    location = geolocator.reverse(f"{lat}, {lng}")
    #print("lox")
    # Extract the district information from the address
    address = location.raw['address']
    district = address.get('suburb', address.get('city_district'))
    return district

# Apply the get_district function to each row of the data
data['district'] = data.apply(lambda row: get_district(row['x'], row['y']), axis=1)

/var/folders/31/mgjvydd530n_q8xd9pnv0wrc0000gq/T/ipykernel_90063/1102109162.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['district'] = data.apply(lambda row: get_district(row['x'], row['y']), axis=1)

### rent and sales real-estate

In [23]:
sale = yerevan_actual.loc[(yerevan_actual["rent_or_sale"]=="sale appartments") | (yerevan_actual["rent_or_sale"]=="sale houses")]
rent = yerevan_actual.loc[(yerevan_actual["rent_or_sale"]=="rent houses") | (yerevan_actual["rent_or_sale"]=="rent appartments")]

In [36]:
rent[rent["id"]==18229350]

,OBJECTID,level_0,index,id,price,rooms,square_meters,address,date,source,...,renovation,price_per_meter,floor,building_floors,height,bathroom,rent_or_sale,links,x,y
20233,20234,22298,1,18229350,NaN,3.0,65.0,"Ֆրունզեի փողոց, Երևան",2023-03-13 21:07:15,list.am,...,Designer Renovation,NaN,NaN,1,NaN,2.0,rent houses,http://list.am/en/item/18229350,44.495487,40.147234
20534,20535,22826,529,18229350,NaN,3.0,65.0,"Ֆրունզեի փողոց, Երևան",2023-03-13 21:10:17,list.am,...,Designer Renovation,NaN,NaN,1,NaN,2.0,rent houses,http://list.am/en/item/18229350,44.495487,40.147234
21679,21680,25031,2734,18229350,NaN,3.0,65.0,"Ֆրունզեի փողոց, Երևան",2023-03-13 21:23:08,list.am,...,Designer Renovation,NaN,NaN,1,NaN,2.0,rent houses,http://list.am/en/item/18229350,44.495487,40.147234
22040,22041,25697,3400,18229350,NaN,3.0,65.0,"Ֆրունզեի փողոց, Երևան",2023-03-13 21:26:59,list.am,...,Designer Renovation,NaN,NaN,1,NaN,2.0,rent houses,http://list.am/en/item/18229350,44.495487,40.147234
22558,22559,26708,4411,18229350,NaN,3.0,65.0,"Ֆրունզեի փողոց, Երևան",2023-03-13 21:32:59,list.am,...,Designer Renovation,NaN,NaN,1,NaN,2.0,rent houses,http://list.am/en/item/18229350,44.495487,40.147234
22619,22620,26818,4521,18229350,NaN,3.0,65.0,"Ֆրունզեի փողոց, Երևան",2023-03-13 21:33:38,list.am,...,Designer Renovation,NaN,NaN,1,NaN,2.0,rent houses,http://list.am/en/item/18229350,44.495487,40.147234
23136,23137,28075,5778,18229350,NaN,3.0,65.0,"Ֆրունզեի փողոց, Երևան",2023-03-13 21:40:47,list.am,...,Designer Renovation,NaN,NaN,1,NaN,2.0,rent houses,http://list.am/en/item/18229350,44.495487,40.147234
23262,23263,28493,6196,18229350,NaN,3.0,65.0,"Ֆրունզեի փողոց, Երևան",2023-03-13 21:43:05,list.am,...,Designer Renovation,NaN,NaN,1,NaN,2.0,rent houses,http://list.am/en/item/18229350,44.495487,40.147234

In [35]:
rent

,OBJECTID,level_0,index,id,price,rooms,square_meters,address,date,source,...,renovation,price_per_meter,floor,building_floors,height,bathroom,rent_or_sale,links,x,y
20233,20234,22298,1,18229350,NaN,3.0,65.0,"Ֆրունզեի փողոց, Երևան",2023-03-13 21:07:15,list.am,...,Designer Renovation,NaN,NaN,1,NaN,2.0,rent houses,http://list.am/en/item/18229350,44.495487,40.147234
20234,20235,22299,2,19031770,NaN,2.0,60.0,"Սասունցի Դավթի փողոց 86/6, Երևան",2023-03-13 21:07:15,list.am,...,Designer Renovation,NaN,NaN,1,NaN,1.0,rent houses,http://list.am/en/item/19031770,44.524368,40.151963
20235,20236,22300,3,19066438,NaN,4.0,120.0,"Գերցենի փողոց 3, Երևան",2023-03-13 21:07:15,list.am,...,Euro Renovation,NaN,NaN,4+,NaN,2.0,rent houses,http://list.am/en/item/19066438,44.550904,40.201514
20236,20237,22302,5,19135588,NaN,NaN,390.0,"Հրաչյա Աճառյան փողոց, Երևան",2023-03-13 21:07:16,list.am,...,Cosmetic Renovation,NaN,NaN,3,NaN,3.0,rent houses,http://list.am/en/item/19135588,44.565089,40.218119
20237,20238,22303,6,18193366,NaN,4.0,750.0,"Gusan Sheram Street 76/5, Yerevan",2023-03-13 21:07:16,list.am,...,Designer Renovation,NaN,NaN,1,NaN,1.0,rent houses,http://list.am/en/item/18193366,44.439576,40.179096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51886,51887,820,40,42615,NaN,NaN,800.0,Բաբայան 25/1,2023-03-13 18:57:11,estate.am,...,NaN,NaN,3,NaN,NaN,NaN,rent houses,https://www.estate.am/առանձնատան-վաճառք-արաբկի...,44.515286,40.198634
51887,51888,821,41,114930,3000.000000,NaN,240.0,Նորքի 5-րդ,2023-03-13 18:57:12,estate.am,...,NaN,12.500000,2,NaN,NaN,NaN,rent houses,https://www.estate.am/վարձով-առանձնատուն-նորք-...,44.544392,40.184904
51888,51889,822,42,114930,367.827366,NaN,240.0,Նորքի 5-րդ,2023-03-13 18:57:12,estate.am,...,NaN,1.532614,2,NaN,NaN,NaN,rent houses,https://www.estate.am/վարձով-առանձնատուն-նորք-...,44.544392,40.184904
51889,51890,825,45,114875,735.654733,NaN,70.0,Սևքարեցի Սաքո 1/2,2023-03-13 18:57:14,estate.am,...,NaN,10.509353,1,NaN,NaN,NaN,rent houses,https://www.estate.am/վարձով-առանձնատուն-արաբկ...,44.492523,40.206322
51891,51892,835,55,114357,3200.000000,NaN,360.0,Արաբկիր,2023-03-13 18:57:19,estate.am,...,NaN,8.888889,3,NaN,NaN,NaN,rent houses,https://www.estate.am/առանձնատան-վաճառք-արաբկի...,44.509420,40.207286